/* <sc-table> DEMO_DB.DimSalesReason </sc-table> */
CREATE SET TABLE DEMO_DB.DimSalesReason,
	NO FALLBACK,
	NO BEFORE JOURNAL,
	NO AFTER JOURNAL,
	CHECKSUM = DEFAULT,
	DEFAULT MERGEBLOCKRATIO
	(
		EmployeeKey INTEGER NOT NULL,
		ParentEmployeeKey INTEGER,
		EmployeeNationalIDAlternateKey VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
		FirstName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
		NameStyle BYTEINT CHECK ( NameStyle  IN (0 ,1 ) ) NOT NULL,
		"Title" VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
		HireDate DATE FORMAT 'yyyy-mm-dd',
		PayFrequency BYTEINT,
		BaseRate NUMBER(18,4),
		VacationHours SMALLINT,
		EmployeePhoto BLOB(2097088000),
		Weight NUMBER,
		SalesOrderLineNumber SMALLINT NOT NULL COMPRESS (1 ,2 ,3 ),
		SalesReasonKey INTEGER NOT NULL COMPRESS (1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ),
		EmailAddress VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS USING TD_SYSFNLIB.TRANSUNICODETOUTF8 DECOMPRESS USING TD_SYSFNLIB.TRANSUTF8TOUNICODE,
		EnglishEducation VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Bachelors','Partial College','High School','Graduate Degree','Partial High School'),
		EMPLOYMENT_PERIOD PERIOD(DATE) FORMAT 'YYYY-MM-DD',
		INTERVAL_YEAR_TYPE INTERVAL YEAR(2),
		INTERVAL_MONTH_TYPE INTERVAL MONTH(2),
		SALARY_AMOUNT DECIMAL(10,2) NOT NULL,
		TS TIMESTAMP(6),
	
PRIMARY KEY ( EmployeeKey ))
;


