/* <sc-table> DEMO_DB.INTERVAL_DATA_TYPE  </sc-table> */
CREATE SET TABLE DEMO_DB.INTERVAL_DATA_TYPE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      INTERVAL_YEAR_TYPE INTERVAL YEAR(2),
      INTERVAL_MONTH_TYPE INTERVAL MONTH(2),
      INTERVAL_YEAR2MONTH_TYPE INTERVAL YEAR(2) TO MONTH,
      INTERVAL_DAY_TYPE INTERVAL DAY(2),
      INTERVAL_DAY2HOUR_TYPE INTERVAL DAY(2) TO HOUR,
      INTERVAL_DAY2MINUTE_TYPE INTERVAL DAY(2) TO MINUTE,
      INTERVAL_DAY2SECOND_TYPE INTERVAL DAY(2) TO SECOND(6),
      INTERVAL_HOUR_TYPE INTERVAL HOUR(2),
      INTERVAL_HOUR2MINUTE_TYPE INTERVAL HOUR(2) TO MINUTE,
      INTERVAL_HOUR2SECOND_TYPE INTERVAL HOUR(2) TO SECOND(6),
      INTERVAL_MINUTE_TYPE INTERVAL MINUTE(2),
      INTERVAL_MINUTE2SECOND_TYPE INTERVAL MINUTE(3) TO SECOND(3),
      INTERVAL_SECOND_TYPE INTERVAL SECOND(2,6))
PRIMARY INDEX ( INTERVAL_YEAR_TYPE );

