/* <sc-table> DEMO_DB.ACT_COUNT  </sc-table> */
CREATE MULTISET TABLE DEMO_DB.ACT_COUNT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ACT_COUNT INTEGER,
      LOCATION VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( ACT_COUNT );

