/* <sc-table> DEMO_DB.EMPLOYEE_PERIOD  </sc-table> */
CREATE SET TABLE DEMO_DB.EMPLOYEE_PERIOD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EMPLOYEE_NUMBER INTEGER NOT NULL,
      MANAGER_EMPLOYEE_NUMBER INTEGER,
      DEPARTMENT_NUMBER INTEGER,
      JOB_CODE INTEGER,
      LAST_NAME CHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      FIRST_NAME VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SALARY_AMOUNT DECIMAL(10,2) NOT NULL,
      BIRTHDATE DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      JOB_DURATION PERIOD(DATE) FORMAT 'YYYY-MM-DD' NOT NULL)
PRIMARY INDEX ( EMPLOYEE_NUMBER );


