/* <sc-table> DEMO_DB.FLIGHTS </sc-table> */
CREATE SET TABLE DEMO_DB.FLIGHTS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DESTINATION VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      SOURCE VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      COST INTEGER)
PRIMARY INDEX ( DESTINATION );


