/* <sc-view> DEMO_DB.INTERVAL_DATA_TYPE_V </sc-view> */
-- INTERVAL, PERIOD TYPES, SELECT * LOCKING ROW FOR ACCESS, QUALIFY ***/
REPLACE VIEW DEMO_DB.INTERVAL_DATA_TYPE_V
AS 
LOCKING ROW FOR ACCESS
SELECT * FROM DEMO_DB.INTERVAL_DATA_TYPE;

