/* <sc-view> DEMO_DB.PERIOD_INTERVAL_BEGIN </sc-view> */
REPLACE VIEW DEMO_DB.PERIOD_INTERVAL_BEGIN
AS
SELECT
  PEP.PERSON_ID,
  CAST(BEGIN(PEP.EMPLOYMENT_PERIOD) AS TIMESTAMP)    AS BEGINEMPLOYMENT,
  PL.LOGIN_DTM,
  INTERVAL(
    PERIOD(
      CAST(BEGIN(PEP.EMPLOYMENT_PERIOD) AS TIMESTAMP),
      PL.LOGIN_DTM
    )
  ) HOUR(4) AS HOURSBEFOREFIRSTLOGIN
FROM DEMO_DB.PERSON_EMPLOYMENT_PERIOD    AS PEP
JOIN DEMO_DB.PERSON_LOGIN                AS PL
  ON PEP.PERSON_ID = PL.PERSON_ID
QUALIFY RANK() OVER (
  PARTITION BY PL.PERSON_ID
  ORDER BY PL.LOGIN_DTM
) = 1;


